# A credential-free example: it only writes a local file, so you can run init / plan / apply immediately
# without any cloud account. Great for a first walk through Fenrix's plan-and-apply flow.

resource "random_id" "suffix" {
  byte_length = var.suffix_length
}

locals {
  file_name = "greeting-${random_id.suffix.hex}.txt"
  file_path = "${path.module}/${var.output_dir}/${local.file_name}"
}

resource "local_file" "greeting" {
  filename = local.file_path
  content  = "${var.greeting}\n\nGenerated by Terraform, driven by Fenrix.\n"
}
