// <auto-generated />
using System;
using Fenrix.IaCStudio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fenrix.IaCStudio.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728142746_AddDeploymentPipelines")]
    partial class AddDeploymentPipelines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Cloud.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Cloud.CloudConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastTestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SecretReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionOrProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantOrAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("ProviderType");

                    b.ToTable("CloudConnections", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Cloud.RepositoryConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastTestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Organisation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectOrWorkspace")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SecretReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("ProviderType");

                    b.ToTable("RepositoryConnections", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Environments.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackendConfigFile")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CloudConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitBranchPolicy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerraformWorkspace")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariablesFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CloudConnectionId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Execution.CommandRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputLogPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedactedArguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("ProjectId", "StartedAt");

                    b.ToTable("CommandRuns", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Files.FileBlob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.ToTable("FileBlobs", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Files.FileIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CurrentRelativePath");

                    b.HasIndex("ProjectId", "IsDeleted");

                    b.ToTable("FileIdentities", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Files.FileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BlobId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CapturedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommit")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlobId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("FileIdentityId", "CapturedAt");

                    b.ToTable("FileVersions", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Projects.InfrastructureProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLinked")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastOpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RepositoryConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryRootPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredTerraformVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Projects.RecentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CursorColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursorLine")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastOpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastOpenedAt");

                    b.HasIndex("ProjectId");

                    b.ToTable("RecentFiles", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Security.KeyPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Bits")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CloudConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudKeyName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastExportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeyOpenSsh")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationWorkingDir")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SecretReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("KeyPairs", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Security.SecretReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SecretReferences");
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Settings.SettingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Scope", "ScopeId")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Terraform.SavedPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AddCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Applied")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AppliedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ApplyCommandRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CloudConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestroyCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("GitTreeDirty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvalidatedReason")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInvalidated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProductionTarget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlanCommandRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanFileHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePlanFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplaceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TerraformVersion")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "CreatedAt");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("SavedPlans", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Versioning.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AddCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestroyCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLockHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplaceCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateBackend")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateLineage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StateSerial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TerraformVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectVersionId");

                    b.HasIndex("EnvironmentId", "Status");

                    b.ToTable("Deployments", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Versioning.DeploymentPipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DeploymentPipelines", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Versioning.PipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Approvers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireCleanWorkingTree")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequirePreviousStageSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireTypedConfirmationForProduction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredBranch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("PipelineId");

                    b.ToTable("PipelineStages", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Versioning.ProjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLockHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredTerraformVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectVersions", (string)null);
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Environments.ProjectEnvironment", b =>
                {
                    b.HasOne("Fenrix.IaCStudio.Domain.Projects.InfrastructureProject", null)
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Versioning.PipelineStage", b =>
                {
                    b.HasOne("Fenrix.IaCStudio.Domain.Versioning.DeploymentPipeline", null)
                        .WithMany("Stages")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Projects.InfrastructureProject", b =>
                {
                    b.Navigation("Environments");
                });

            modelBuilder.Entity("Fenrix.IaCStudio.Domain.Versioning.DeploymentPipeline", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
